version: '3'

services:
  api_enterprise_management:
    image: bitnami/mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root
