# Generated by Django 4.2 on 2023-04-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='department',
            name='department_id_index',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_id_index',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_id_index',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employee_department_index'),
        ),
    ]
