# Generated by Django 4.2 on 2023-04-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_remove_department_department_id_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(),
        ),
    ]
