# Generated by Django 4.2 on 2023-04-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='employee_projects', through='src.ProjectEmployee', to='src.project'),
        ),
    ]
