# Generated by Django 4.2 on 2023-04-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_project_completed_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='any'),
            preserve_default=False,
        ),
    ]
