# Generated by Django 4.2 on 2023-04-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_project_end_date_project_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectemployee',
            old_name='employee_workload',
            new_name='hours_worked_per_week',
        ),
    ]
